services:
  vehicule-app:
    image: vehicule-app
    container_name: vehicule-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=vehicule
      - DB_USER=group10
      - DB_PASSWORD=10-sftw-testing-java
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_DB: vehicule
      POSTGRES_USER: group10
      POSTGRES_PASSWORD: 10-sftw-testing-java
    ports:
      - "5433:5432"