services:
  vehicule-app:
    image: vehicule-app
    container_name: vehicule-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_DB: vehicule
      POSTGRES_USER: group10
      POSTGRES_PASSWORD: 10-sftw-testing-java
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
