name: Propelize Full CI

on:
  push:
    branches: [ "main", "imelda" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      ####################################
      ## FRONTEND TESTS (Playwright)
      ####################################

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/properlize/yarn.lock

      - name: Install frontend dependencies
        working-directory: ./frontend/properlize
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        working-directory: ./frontend/properlize
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./frontend/properlize
        run: npx playwright test

      - name: Upload Playwright report on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: frontend/properlize/playwright-report/
          retention-days: 7

      ####################################
      ## BACKEND TESTS (Maven + JaCoCo)
      ####################################

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  # ajuste si besoin

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run backend tests and generate JaCoCo report
        working-directory: ./vehicule
        run: mvn clean verify

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: vehicule/target/site/jacoco/
          retention-days: 7
